import Foundation
import SwiftProtobufPluginLibrary

@main
struct ActrFrameworkGenerator {
    static let version = "0.1.2"

    static func main() throws {
        // Handle command line arguments
        if CommandLine.arguments.contains("--version") || CommandLine.arguments.contains("-v") {
            print(version)
            return
        }

        // Read the request from stdin
        let requestData = FileHandle.standardInput.readDataToEndOfFile()
        let request = try Google_Protobuf_Compiler_CodeGeneratorRequest(serializedBytes: requestData)

        var response = Google_Protobuf_Compiler_CodeGeneratorResponse()

        for fileDescriptor in request.protoFile {
            if fileDescriptor.service.isEmpty { continue }

            var content = """
            // DO NOT EDIT.
            // Generated by protoc-gen-actrframework-swift

            import Foundation
            import SwiftProtobuf
            import Actr

            """

            // Determine the prefix for Swift types based on package name
            // SwiftProtobuf usually removes underscores and camelCases the package name
            let packagePrefix = fileDescriptor.package.isEmpty ? "" : fileDescriptor.package.split(separator: "_").map { $0.capitalized }.joined() + "_"
            let protoPackage = fileDescriptor.package

            for service in fileDescriptor.service {
                let serviceName = service.name
                let handlerProtocol = "\(serviceName)Handler"

                content += """

                /// \(serviceName) service handler protocol - users need to implement this protocol
                ///
                /// Example implementation:
                /// ```swift
                /// struct My\(serviceName)Handler: \(handlerProtocol) {
                """

                for method in service.method {
                    let methodName = method.name.prefix(1).lowercased() + method.name.dropFirst()
                    let inputType = packagePrefix + method.inputType.split(separator: ".").last!
                    let outputType = packagePrefix + method.outputType.split(separator: ".").last!

                    content += """

                    ///     func \(methodName)(req: \(inputType), ctx: ContextBridge) async throws -> \(outputType) {
                    ///         return \(outputType)()
                    ///     }
                    """
                }

                content += """

                /// }
                /// ```
                public protocol \(handlerProtocol): Sendable {
                """

                for method in service.method {
                    let methodName = method.name.prefix(1).lowercased() + method.name.dropFirst()
                    let inputType = packagePrefix + method.inputType.split(separator: ".").last!
                    let outputType = packagePrefix + method.outputType.split(separator: ".").last!

                    content += """

                        /// RPC method: \(method.name)
                        func \(methodName)(
                            req: \(inputType),
                            ctx: ContextBridge
                        ) async throws -> \(outputType)

                    """
                }

                content += "\n}\n"
            }

            var generatedFile = Google_Protobuf_Compiler_CodeGeneratorResponse.File()
            // Change suffix from .actr.swift to .actor.swift
            generatedFile.name = fileDescriptor.name.replacingOccurrences(of: ".proto", with: ".actor.swift")
            generatedFile.content = content
            response.file.append(generatedFile)
        }

        // Write the response back to stdout
        try FileHandle.standardOutput.write(response.serializedData())
    }
}
